spring:
  application:
    name: spotify-macros

  profiles:
    active: local  # one of many spring profiles -> local, dev, test, prod(production)
                   # local means start the app in local mode:
                   #     application.yml + application-local.yml

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/spotify"
            scope:
              - user-read-playback-state
              - user-modify-playback-state
              - playlist-read-private

        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id
