spring:
  application:
    name: spotify-macros

  profiles:
    active: local  # one of many spring profiles -> local, dev, test, prod(production)
                   # local means start the app in local mode:
                   #     application.yml + application-local.yml
logging:
  level:
    org.springframework.security: TRACE

server:
  servlet:
    session:
      cookie:
        secure: true